UploadRuc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
]

core/urls.py
from django.urls import path
from .import views

app_name = 'core'

urlpatterns = [
    
    path('',views.index, name='index'),
    path('upload_ruc/',views.upload_ruc, name='upload_ruc'),
    path('visualize_ruc/',views.visualize_ruc, name='visualize_ruc'),
    path('sort_ruc_timsort/', views.sort_ruc_timsort, name= 'sort_ruc_timsort'),
    path('sort_quicksort/', views.sort_quicksort, name= 'sort_quicksort')

]

core/models.py
from django.db import models




class Ruc(models.Model):
    document = models.CharField(max_length=50)
    name = models.CharField(max_length=255)
    code  =  models.CharField(max_length=20)
    key = models.CharField(max_length=20)
    
    def __str__(self):
        return f'{self.code} - {self.name}'
    
    
    
class ChargeRuc(models.Model):
    name_arc = models.CharField(max_length=255)
    date_charge = models.DateTimeField(auto_now_add=True)
    record = models.PositiveIntegerField()
    
    def __str__(self):
        return f'{self.name_arc} - {self.date_charge.strftime("%Y-%m-%d %H:%M:%S")}'    

core/forms.py
from django.forms import forms
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField(label='')
    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)
        self.fields['file'].widget.attrs['class']  = 'form-control'
        self.fields['file'].widget.attrs['style'] = 'width: 85%; float:left'

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
from core.forms import UploadFileForm
from core.models import Ruc, ChargeRuc
from io import BytesIO
from reportlab.platypus import SimpleDocTemplate,\
Paragraph, Table, Spacer, TableStyle
from reportlab.lib.pagesizes import A4, portrait
from core.functions import timSort, quicksort
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import pandas as pd


def index(request):
    template_name = 'core/index.html'
    upload_history = ChargeRuc.objects.all().order_by('-date_charge')[:10]
    return render(request, template_name, {'upload_history': upload_history})



def upload_ruc(request):
    template_name = 'core/upload.html'
    form = UploadFileForm(request.POST or None)
    
    if request.POST:
        form= UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                uploaded_file = request.FILES['file']
                uploaded_file.seek(0)
                try:
                    df = pd.read_csv(uploaded_file, sep = '|',encoding = 'latin1', header= None)
                except Exception as e:
                    print(f"error reading file with '|': {e}")
                    uploaded_file.seek(0)
                    df = pd.read_csv(uploaded_file, sep = '\t',encoding = 'latin1', header= None)
                
                df = df.dropna(how='all')
                df = df[df[0].notna() & df[1].notna() & df[2].notna() & df[3].notna()]
                df = df.head(50)
                for _, row in df.iterrows():
                    if len(row) >= 4:
                        Ruc.objects.create(
                            document = str(row[0]).strip(),
                            name = str(row[1]).strip(),
                            code = str(row[2]).strip(),
                            key = str(row[3]).strip()
                        )
                    else:
                        print(f"ignored row for invalid format: {row}")
                ChargeRuc.objects.create(name_arc = uploaded_file.name, record = df.shape[0])
                messages.success(request, 'file uploaded to database successfully!')
                return redirect('core:visualize_ruc')
            except Exception as e:
                print(e)
                messages.error(request, f'error uploading file {e}.')
    return render(request, template_name, {'form': form})    




def visualize_ruc(request):
    template_name = 'core/visualize_ruc.html'
    ruc_data = Ruc.objects.all()[:50]

    if request.POST.get('accion') == 'PDF':
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="reporte_ruc.pdf"'
        buff = BytesIO()

        doc = SimpleDocTemplate(buff,
                                 pagesize=portrait(A4),
                                 rightMargin=60,
                                 leftMargin=60,
                                 topMargin=20,
                                 bottomMargin=45)
        
        doc.title = 'RUC PDF'

        
        styles = getSampleStyleSheet()
        text_center = styles['Normal']
        text_center.fontSize = 8
        text_center.leading = 10
        text_center.alignment = 1  

        text_right = styles['Normal']
        text_right.fontSize = 8
        text_right.leading = 8
        text_right.alignment = 2 

        text_left = styles['Normal']
        text_left.fontSize = 8
        text_left.leading = 8
        text_left.alignment = 0

       
        story = []

        title = Paragraph("Ruc report", text_center)
        story.append(title)
        story.append(Spacer(1, 12))

        data = [['id','document', 'name', 'code' , 'key']] 
        for ruc in ruc_data:
            data.append([ruc.id, ruc.document, ruc.name, ruc.code, ruc.key])  

        table = Table(data)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        
        story.append(table)

        doc.build(story)

        pdf = buff.getvalue()
        buff.close()
        response.write(pdf)
        return response

    return render(request, template_name, {'ruc_data': ruc_data})



def sort_ruc_timsort(request):
    template_name = 'core/visualize_ruc.html'
    ruc_data = Ruc.objects.all()[:50]

    names = [ruc.name for ruc in ruc_data]
    
    timSort(names)


    ruc_data_sorted = []
    
    for name in names:
        for ruc in ruc_data:
            if ruc.nombre == names:
                ruc_data_sorted.append(ruc)
                break


    return render(request, template_name, {'ruc_data':ruc_data_sorted})




def sort_quicksort(request):
    template_name = 'core/visualize_ruc.html'
    ruc_data = Ruc.objects.all()[:50]
    
    names = [str(ruc.name) for ruc in ruc_data]
    
    quicksort(names,0 , len(names)-1)
    
    ruc_data_sorted = []
    
    for name in names:
        for ruc in ruc_data:
            if ruc.name == name:
                ruc_data_sorted.append(ruc)
                break
    return render(request, template_name, {'ruc_data': ruc_data_sorted})

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">

        <title>Manager</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'core/styles.css' %}">
    </head>
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

    </body>
    </html>

core/templates/core/index.html
{% extends "base.html" %}

{% block title %}

rucs viewer
{% endblock %}

{% block content %}


<h1>Welcome to The Ruc System</h1>

<h2>Recent Upload History</h2>

{% if upload_history %}
    <table border="1">
        <thead>
            <tr>
                <th>Archive</th>
                <th>Upload date</th>
                <th>Uploaded records</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for charge in upload_history %}
                <tr>
                    <td>{{ chargecarga.name_arc }}</td>
                    <td>{{ charge.fecha_carga|date:"d/m/Y H:i" }}</td>
                    <td>{{ charge.registros }}</td>
                    <td>
                        <a href="{% url 'core:visualize_ruc' %}">View RUC</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Theres nothing available.</p>
{% endif %}



<div  style="float: left; width:65%; font-size: 1.2em;">
    <tr>
        <td align = "right">
            <a style="margin-top:5px; padding:4px 5px; background:#00a133" href="{% url 'core:upload_ruc' %}" class="btn btn-xs btn-default" role="button"><i class="fa fa-address-card"  aria-hidden="true"></i> Go to upload file</a>
        </td>
    </tr>
</div>
{% endblock %}

core/templates/core/upload.html
{% extends "base.html" %}

{% block title %}

{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload File</button>
    <a href="{{request.META.HTTP_REFERER}}" class="btn btn-secondary">Cancel</a>
</form>


{% endblock %}

core/templates/core/visualize_ruc.html
{% extends 'base.html' %}

{% block content %}
    <h2>List of RUC - first 50 records </h2>
    <a href="{% url 'core:sort_ruc_timsort' %}" class="btn btn-secondary">Sort by timsort</a>
    <a href="{% url 'core:sort_quicksort' %}" class="btn btn-secondary">Sort by quicksort</a>
    <form method="POST" action="{% url 'core:visualize_ruc' %}">
        {% csrf_token %}
        <button type="submit" name="accion" class="btn btn-sm btn-danger" value="PDF">
            <span class="fa fa-file-pdf-o" aria-hidden="true"></span> <strong>PDF</strong>
        </button>
    </form>
    {% if ruc_data %}
        <table border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Document</th>
                    <th>Name</th>
                    <th>code</th>
                    <th>key</th>
                </tr>
            </thead>
            <tbody>
                {% for ruc in ruc_data %}
                    <tr>
                        <td>{{ ruc.id }}</td>
                        <td>{{ ruc.document }}</td>
                        <td>{{ ruc.name }}</td>
                        <td>{{ ruc.code }}</td>
                        <td>{{ ruc.key }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
            <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">start</a>

    {% else %}
        <p>Theres nothing available.</p>
    {% endif %}
{% endblock %}